language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - composer require --dev php-coveralls/php-coveralls
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls