language: php

php:
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - composer require --dev php-coveralls/php-coveralls
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - vendor/bin/phpunit